FROM oven/bun

WORKDIR /app

ARG ORIGIN
ARG PUBLIC_GHOST_URL
ARG PUBLIC_GHOST_KEY
ARG PUBLIC_PB_URL

# Set environment variables
ENV ORIGIN=${ORIGIN}
ENV PUBLIC_GHOST_URL=${PUBLIC_GHOST_URL}
ENV PUBLIC_GHOST_KEY=${PUBLIC_GHOST_KEY}
ENV PUBLIC_PB_URL=${PUBLIC_PB_URL}

COPY package*.json bun.lock ./

RUN bun install

COPY . .

RUN bun run build

EXPOSE 3000

CMD [ "bun", "start" ]
